query CartPageQuery {
  products(locale: "all", where: { isRecommended: true }) {
    description
    id
    imageSmall {
      url
    }
    locale
    name
    priceDefault
    priceDiscounted
    slug
    quantity
    weight
  }
}
