query HomePageQuery {
  products(locale: "all", where: { isRecommended: true }) {
    description
    id
    imageSmall {
      url
    }
    locale
    name
    priceDefault
    priceDiscounted
    quantity
    weight
  }

  slides(locale: "all") {
    image {
      url
    }
    title
  }
}
