query ProductPageQuery($slug: String!) {
  productBySlug(slug: $slug) {
    id
    description
    name
    priceDefault
    weight
    quantity
    imageSmall {
      url
    }
    imageMain {
      url
    }
  }
}
