query ShopPageQuery($where: JSON) {
  products(locale: "all", where: $where) {
    description
    id
    imageSmall {
      url
    }
    locale
    name
    priceDefault
    priceDiscounted
    slug
    quantity
    weight
  }

  categories(locale: "all") {
    name
    slug
  }
}
